#!/usr/bin/env python3
"""
Rebuild v3 — carousel pages 6-10 of the Shell Scripting for DevOps handbook.

This is the v3 rebuild. Unlike the prior rebuilds (rebuild-pages-1-5.py etc.),
this one uses the canonical `polotno_template.py` module:

    from polotno_template import page_wrapper, multi_page_html

Each page is generated by:
    1. Building a `content_html` string (title + sections + tip).
    2. Wrapping it via `page_wrapper(content_html, paper_height=1424,
       page_id="pN")` so we get the Polotno notebook paper, holes, spiral
       binding rings, 3D page-stack edges, and the standard content padding.
    3. Wrapping that single page in `multi_page_html([page], title)` to get a
       full standalone HTML document.

Colorful multi-color filled SVG icons come from `shell_scripting_icons.py`:
    from shell_scripting_icons import icon

NO VERIQTA branding. NO social-media footer. Each page stands on its own.

Layouts (per task brief):
    Page 6  — Variables & Environment Variables   → 3-column card grid
    Page 7  — Exit Codes & Command Success         → 3-column card grid
    Page 8  — Conditional Statements               → 3-column card grid
    Page 9  — Logical Operators & Multi Conditions → single-column centered
    Page 10 — Loops for Automation                  → 2-column card grid

Writes:
    downloads/instagram-DcaW1UljsVk/recreated-page-06.html
    downloads/instagram-DcaW1UljsVk/recreated-page-07.html
    downloads/instagram-DcaW1UljsVk/recreated-page-08.html
    downloads/instagram-DcaW1UljsVk/recreated-page-09.html
    downloads/instagram-DcaW1UljsVk/recreated-page-10.html
"""

import os
import sys

# Make sibling modules importable
SCRIPTS_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, SCRIPTS_DIR)

from polotno_template import page_wrapper, multi_page_html  # noqa: E402
from shell_scripting_icons import icon  # noqa: E402

PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPTS_DIR, ".."))
OUT_DIR = os.path.join(
    PROJECT_ROOT, "downloads", "instagram-DcaW1UljsVk"
)

# ============================================================
# Color palette (matches the original carousel's dark-green brand)
# ============================================================
GREEN = "#1B5E3F"          # primary brand green (dark forest)
GREEN_DARK = "#164a32"
GREEN_2 = "#2E7D32"
NAVY = "#15264d"
BLUE = "#2563eb"
RED = "#dc2626"
GOLD = "#d4a017"
AMBER = "#f9a825"
PURPLE = "#7c3aed"
ORANGE = "#e65100"
TEAL = "#0d7377"
INK = "#1c1c1c"
INK_2 = "#3a3f47"
PAPER = "#f5f1e8"
CODE_BG = "#0d1117"        # terminal dark background
CODE_FG = "#e6edf3"        # terminal default text

# ============================================================
# Shared content CSS — inlined into every page's <style> block.
# Sits ON TOP of the .content div that polotno_template.page_wrapper
# produces. Targets: title row, page badge, cards, terminals, tables,
# bullet lists, tip bar.
# ============================================================
SHARED_CSS = """
/* ===== Override polotno_template's .content positioning =====
   The template ships .content as position:relative, which causes it to be
   pushed BELOW the inline paper-svg (which takes a full line-box height).
   Force absolute so content overlays the paper SVG inside the .paper div.
   The inline padding (42px 50px 26px 78px) is preserved. */
.content{
  position:absolute !important;
  top:11px !important;
  left:0 !important;
  right:0 !important;
  bottom:11px !important;
  --green:#1B5E3F; --green-2:#2E7D32; --green-dk:#164a32;
  --navy:#15264d; --blue:#2563eb; --red:#dc2626;
  --gold:#d4a017; --amber:#f9a825; --orange:#e65100;
  --purple:#7c3aed; --teal:#0d7377;
  --ink:#1c1c1c; --ink-2:#3a3f47;
  --paper:#f5f1e8;
  --term-bg:#0d1117; --term-fg:#e6edf3;
  --card-bg:#ffffff; --card-border:rgba(22,38,77,0.10);
  font-family:"Inter","Segoe UI",Roboto,Helvetica,Arial,sans-serif;
  color:var(--ink);
  overflow:auto;
}

/* ===== Brand bar (page badge top-right) ===== */
.brand-bar{
  display:flex;align-items:center;justify-content:space-between;
  margin-bottom:12px;
}
.brand-bar .crumb{
  font-size:11px;font-weight:700;letter-spacing:1.6px;
  color:var(--green);text-transform:uppercase;
  display:flex;align-items:center;gap:8px;
}
.brand-bar .badge{
  background:#fff;color:var(--green);
  padding:5px 13px;border-radius:999px;
  border:2px solid var(--green);
  font-size:11px;font-weight:800;letter-spacing:.8px;text-transform:uppercase;
}

/* ===== Page title row ===== */
.page-title{
  display:flex;align-items:center;justify-content:center;gap:13px;
  margin:2px 0 4px;
}
.page-title .ico{flex-shrink:0;display:flex;align-items:center;gap:6px;}
.page-title .ico svg{width:38px;height:38px;display:block;}
.page-title h1{
  font-size:30px;font-weight:800;color:var(--green);
  text-transform:uppercase;letter-spacing:-.4px;line-height:1.05;
  text-align:center;margin:0;
}
.page-subtitle{
  font-size:12px;font-weight:700;color:var(--ink-2);
  text-transform:uppercase;letter-spacing:1.4px;text-align:center;
  margin:0 0 14px;
  padding-bottom:8px;
  border-bottom:2px solid var(--green);
  position:relative;
}
.page-subtitle::after{
  content:"";position:absolute;left:50%;bottom:-5px;
  width:9px;height:9px;background:var(--green);
  border-radius:50%;transform:translateX(-50%);
}

/* ===== Grids ===== */
.grid-2{display:grid;grid-template-columns:1fr 1fr;gap:12px;}
.grid-3{display:grid;grid-template-columns:1fr 1fr 1fr;gap:12px;}
.grid-2-uneven{display:grid;grid-template-columns:1.25fr 1fr;gap:12px;}
.col-stack{display:flex;flex-direction:column;gap:11px;}
.row-stack{display:flex;flex-direction:column;gap:12px;}

/* ===== Card ===== */
.card{
  background:var(--card-bg);
  border-radius:9px;
  overflow:auto;
  border:1px solid var(--card-border);
  box-shadow:0 2px 8px rgba(0,0,0,.06);
  display:flex;flex-direction:column;
}
.card .head{
  background:var(--green);color:#fff;
  padding:6px 11px;
  font-size:11px;font-weight:800;letter-spacing:.5px;text-transform:uppercase;
  display:flex;align-items:center;gap:7px;
  border-bottom:2px solid var(--green-dk);
}
.card .head svg{width:15px;height:15px;flex-shrink:0;}
.card .head.navy{background:var(--navy);border-bottom-color:#0a1838;}
.card .head.red{background:var(--red);border-bottom-color:#9a1818;}
.card .head.gold{background:var(--gold);border-bottom-color:#8a6810;color:#1c1c1c;}
.card .head.amber{background:var(--amber);border-bottom-color:#a06b10;color:#1c1c1c;}
.card .head.purple{background:var(--purple);border-bottom-color:#4a1f8a;}
.card .head.blue{background:var(--blue);border-bottom-color:#163b8e;}
.card .head.teal{background:var(--teal);border-bottom-color:#054a4d;}
.card .head.orange{background:var(--orange);border-bottom-color:#8a2f00;}
.card .pad{padding:9px 11px;flex:1;}
.card .pad.tight{padding:7px 9px;}
.card .pad h4{
  font-size:11px;font-weight:800;color:var(--green);
  text-transform:uppercase;letter-spacing:.4px;margin-bottom:5px;
}

/* ===== Inline + block code ===== */
code.inl{
  font-family:"JetBrains Mono","Fira Code","Consolas",monospace;
  font-size:10.5px;font-weight:600;color:var(--green);
  background:#e6efe8;padding:1px 4px;border-radius:3px;
  white-space:nowrap;
}
code.inl.navy{color:var(--navy);background:#e9ecf5;}
code.inl.red{color:var(--red);background:#fbe4e4;}

/* Terminal block (dark) */
.term{
  background:var(--term-bg);color:var(--term-fg);
  border-radius:6px;overflow:auto;
  font-family:"JetBrains Mono","Fira Code","Consolas",monospace;
  font-size:10.5px;line-height:1.5;
  margin-top:5px;
  box-shadow:0 2px 8px rgba(0,0,0,.20);
}
.term .bar{
  background:#1c2230;padding:4px 9px;
  display:flex;align-items:center;gap:5px;
}
.term .dot{width:8px;height:8px;border-radius:50%;}
.term .dot.r{background:#ff5f56;}
.term .dot.y{background:#ffbd2e;}
.term .dot.g{background:#27c93f;}
.term .ttl{margin-left:auto;color:#8b949e;font-size:9px;font-family:monospace;}
.term .body{padding:6px 9px;white-space:pre;overflow-x:auto;}
.term .k{color:#79c0ff;}     /* keywords */
.term .s{color:#7ee787;}     /* strings */
.term .c{color:#8b949e;}     /* comments */
.term .v{color:#f2cc60;}     /* variables */
.term .o{color:#e6edf3;}     /* operators / plain */
.term .r{color:#ff7b72;}     /* red words (if/then/exit etc.) */

/* Light code block (off-white) */
.code-light{
  background:#f4f1e7;border:1px solid #d8d3c0;border-radius:6px;
  padding:6px 9px;
  font-family:"JetBrains Mono","Fira Code","Consolas",monospace;
  font-size:10.5px;line-height:1.5;color:var(--ink);
  white-space:pre;overflow-x:auto;margin-top:5px;
}
.code-light .k{color:#a52a2a;font-weight:700;}
.code-light .s{color:var(--green);font-weight:600;}
.code-light .v{color:#b8860b;}
.code-light .c{color:#8b949e;font-style:italic;}

/* ===== Bullet list ===== */
ul.bul{
  list-style:none;padding:0;margin:4px 0 0;
  display:flex;flex-direction:column;gap:4px;
}
ul.bul li{
  position:relative;padding-left:16px;
  font-size:11px;line-height:1.45;color:var(--ink);
}
ul.bul li::before{
  content:"";position:absolute;left:0;top:5px;
  width:6px;height:6px;border-radius:50%;background:var(--green);
}
ul.bul.ck li{padding-left:20px;}
ul.bul.ck li::before{
  content:"";position:absolute;left:0;top:1px;width:13px;height:13px;
  background:var(--green);border-radius:50%;
  background-image:url("data:image/svg+xml;utf8,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%2024%2024'%20fill='none'%20stroke='white'%20stroke-width='3'%20stroke-linecap='round'%20stroke-linejoin='round'%3E%3Cpolyline%20points='5,13%2010,18%2019,7'/%3E%3C/svg%3E");
  background-size:9px 9px;background-repeat:no-repeat;background-position:center;
  border-radius:50%;
}

/* ===== Data tables ===== */
table.dt{
  width:100%;border-collapse:collapse;
  font-size:10.5px;
}
table.dt th,table.dt td{
  text-align:left;padding:4px 7px;
  border-bottom:1px solid #e6e2d2;
  vertical-align:top;
}
table.dt th{
  background:var(--green);color:#fff;
  font-size:9.5px;font-weight:800;letter-spacing:.4px;text-transform:uppercase;
}
table.dt td code,table.dt td .mono{
  font-family:"JetBrains Mono","Fira Code","Consolas",monospace;
  font-size:10px;color:var(--navy);background:#eef0f6;
  padding:1px 4px;border-radius:3px;white-space:nowrap;
}

/* ===== Output pill ===== */
.out{
  display:inline-flex;align-items:center;gap:5px;
  background:#e6efe8;border:1px solid #b8d6c0;
  border-radius:5px;padding:2px 7px;
  font-size:10.5px;color:var(--green);font-weight:700;
  margin-top:4px;
}
.out svg{width:10px;height:10px;}
.out b{color:var(--green-2);}

/* ===== Status badges (success / failure pills) ===== */
.pill{
  display:inline-flex;align-items:center;gap:5px;
  padding:3px 8px;border-radius:999px;
  font-size:10px;font-weight:800;letter-spacing:.4px;text-transform:uppercase;
}
.pill.ok{background:#e6f4ea;color:var(--green-2);border:1px solid #b8d6c0;}
.pill.no{background:#fce8e8;color:var(--red);border:1px solid #f3c2c2;}

/* ===== Tip bar (bottom of page, no social footer) ===== */
.tip-bar{
  margin-top:12px;
  background:linear-gradient(90deg,var(--green) 0%, var(--green-2) 100%);
  color:#fff;border-radius:9px;
  padding:9px 14px;
  display:flex;align-items:center;gap:10px;
  box-shadow:0 3px 10px rgba(22,38,77,.20);
}
.tip-bar .star{
  flex-shrink:0;width:25px;height:25px;
  background:#fff;border-radius:50%;
  display:flex;align-items:center;justify-content:center;
}
.tip-bar .star svg{width:16px;height:16px;display:block;}
.tip-bar .txt{font-size:11.5px;font-weight:700;line-height:1.35;}
.tip-bar .txt b{font-weight:900;letter-spacing:.4px;}
.tip-bar .code-pill{
  margin-left:auto;flex-shrink:0;
  background:#0d1117;color:#e6edf3;
  padding:4px 9px;border-radius:5px;
  font-family:"JetBrains Mono","Fira Code",monospace;
  font-size:10.5px;font-weight:700;
}

/* ===== Section header (used in single-col pages) ===== */
.sec-head{
  display:flex;align-items:center;gap:9px;
  background:#fff;border:1px solid var(--card-border);
  border-left:4px solid var(--green);
  border-radius:7px;
  padding:7px 13px;margin-bottom:7px;
}
.sec-head .num{
  flex-shrink:0;width:24px;height:24px;border-radius:50%;
  background:var(--green);color:#fff;
  display:flex;align-items:center;justify-content:center;
  font-size:11.5px;font-weight:800;
}
.sec-head h3{
  font-size:12.5px;font-weight:800;color:var(--green);
  text-transform:uppercase;letter-spacing:.5px;margin:0;
}

/* ===== Centered single-column container ===== */
.single-wrap{
  max-width:880px;margin:0 auto;
  display:flex;flex-direction:column;gap:11px;
}

/* ===== Small inline arrow ===== */
.arrow{
  display:inline-flex;align-items:center;gap:3px;
  color:var(--green);font-weight:700;font-size:10.5px;
}
.arrow::after{content:"→";font-weight:900;}

/* ===== Tiny section break ===== */
.brk{height:5px;}

/* ===== Specific helpers ===== */
.center{text-align:center;}
.muted{color:var(--ink-2);}
.small{font-size:10.5px;}
"""

# ============================================================
# Helper builders
# ============================================================

def inline_css(css: str) -> str:
    return f"<style>{css}</style>"


def card(head_text: str, body_html: str, head_cls: str = "",
         head_icon: str = None, head_icon_size: int = 16,
         pad_cls: str = "") -> str:
    """A standard card with green header bar + body."""
    ico = f"{icon(head_icon, head_icon_size)}" if head_icon else ""
    return (
        f'<div class="card">'
        f'<div class="head {head_cls}">{ico}<span>{head_text}</span></div>'
        f'<div class="pad {pad_cls}">{body_html}</div>'
        f'</div>'
    )


def term(code_html: str, title: str = "bash") -> str:
    """Dark terminal block. code_html is pre-formatted with span tags."""
    dots = ('<span class="dot r"></span><span class="dot y"></span>'
            '<span class="dot g"></span>')
    return (
        f'<div class="term">'
        f'<div class="bar">{dots}<span class="ttl">{title}</span></div>'
        f'<div class="body">{code_html}</div>'
        f'</div>'
    )


def code_light(code_html: str) -> str:
    """Light off-white code block."""
    return f'<div class="code-light">{code_html}</div>'


def out(text_html: str) -> str:
    """Output pill: ➔ <text>."""
    return (
        f'<div class="out"><svg viewBox="0 0 24 24" fill="none" stroke="#1B5E3F" '
        f'stroke-width="3" stroke-linecap="round" stroke-linejoin="round">'
        f'<path d="M5 12h14"/><path d="M13 6l6 6-6 6"/></svg>'
        f'<span>Output: <b>{text_html}</b></span></div>'
    )


def tip_bar(text_html: str, code_pill: str = "</>") -> str:
    """Bottom tip bar — no social footer."""
    return (
        f'<div class="tip-bar">'
        f'<div class="star">{icon("star", 18)}</div>'
        f'<div class="txt">{text_html}</div>'
        f'<div class="code-pill">{code_pill}</div>'
        f'</div>'
    )


def page_header(title: str, subtitle: str, page_num_text: str,
                left_icon: str = "terminal",
                right_icon: str = "check-circle") -> str:
    """Standard page header: brand-bar (left crumb + right page badge) +
    centered title row + subtitle."""
    return (
        f'<div class="brand-bar">'
        f'<div class="crumb">Shell Scripting · DevOps Handbook</div>'
        f'<div class="badge">{page_num_text}</div>'
        f'</div>'
        f'<div class="page-title">'
        f'<div class="ico">{icon(left_icon, 42)}</div>'
        f'<h1>{title}</h1>'
        f'<div class="ico">{icon(right_icon, 42)}</div>'
        f'</div>'
        f'<div class="page-subtitle">{subtitle}</div>'
    )


# ============================================================
# PAGE 6 — VARIABLES AND ENVIRONMENT VARIABLES (3-col)
# ============================================================

def build_page_6() -> str:
    title = "4. Variables and Environment Variables"
    subtitle = "Store data. Reuse. Automate."
    page_num = "Page 4"

    header = page_header(title, subtitle, page_num,
                         left_icon="terminal", right_icon="cube")

    # Row 1 — Creating, Reading, Quoting
    row1 = f"""
    <div class="grid-3">
      {card("1. Creating Variables",
        '<ul class="bul">'
        '<li>No spaces around <code class="inl">=</code> sign.</li>'
        '</ul>'
        + code_light(
            '<span class="v">NAME</span>=<span class="s">DevOps</span>\n'
            '<span class="v">COUNT</span>=<span class="s">5</span>'
        ),
        head_icon="pencil", head_icon_size=16)}

      {card("2. Reading Variables",
        '<ul class="bul">'
        '<li>Use <code class="inl">$</code> to read a variable.</li>'
        '</ul>'
        + code_light('<span class="k">echo</span> $NAME')
        + out("DevOps"),
        head_icon="eye", head_icon_size=16)}

      {card("3. Quoting Variables",
        '<ul class="bul">'
        '<li>Use quotes to handle spaces.</li>'
        '<li>Prevents word splitting.</li>'
        '<li>Prevents filename expansion.</li>'
        '</ul>'
        + code_light(
            '<span class="k">echo</span> "$NAME"\n'
            '<span class="k">echo</span> \'$NAME\''
        ),
        head_icon="code", head_icon_size=16)}
    </div>
    """

    # Row 2 — Command Substitution, Export, Environment Variables
    row2 = f"""
    <div class="grid-3">
      {card("4. Command Substitution",
        '<ul class="bul"><li>Store the output of a command.</li></ul>'
        + code_light(
            '<span class="v">DATE</span>=$(<span class="k">date</span> +%Y-%m-%d)\n'
            '<span class="k">echo</span> $DATE'
        )
        + out("2025-05-18"),
        head_icon="terminal", head_icon_size=16)}

      {card("5. Export Variables",
        '<ul class="bul">'
        '<li>Makes a variable available to child processes.</li>'
        '<li>Use <code class="inl">export</code>.</li>'
        '</ul>'
        + code_light(
            '<span class="k">export</span> <span class="v">PROJECT</span>=<span class="s">MyApp</span>\n'
            '<span class="k">echo</span> $PROJECT'
        )
        + out("MyApp"),
        head_icon="arrow", head_icon_size=16)}

      {card("6. Environment Variables",
        '<ul class="bul">'
        '<li>Set by the system.</li>'
        '<li>Available in every shell.</li>'
        '</ul>'
        + term(
            '<span class="k">echo</span> $HOME\n'
            '<span class="k">echo</span> $USER\n'
            '<span class="k">echo</span> $SHELL\n'
            '<span class="k">echo</span> $LANG'
        ),
        head_cls="navy", head_icon="shell", head_icon_size=16)}
    </div>
    """

    # Row 3 — Common Environment Variables (HOME / USER / PATH)
    row3 = f"""
    <div class="grid-3">
      {card("HOME",
        '<div class="small muted">Your home directory.</div>'
        + code_light('<span class="k">echo</span> $HOME')
        + out("/home/user"),
        head_icon="user", head_icon_size=16)}

      {card("USER",
        '<div class="small muted">Current logged-in user.</div>'
        + code_light('<span class="k">echo</span> $USER')
        + out("user"),
        head_icon="user", head_icon_size=16)}

      {card("PATH",
        '<div class="small muted">Directories where commands are searched.</div>'
        + code_light('<span class="k">echo</span> $PATH')
        + out("/usr/bin:/bin:/usr/local/bin"),
        head_icon="search", head_icon_size=16)}
    </div>
    """

    # Row 4 — Using Variables in Scripts + Best Practices (uneven 2-col)
    row4 = f"""
    <div class="grid-2-uneven">
      {card("8. Using Variables in Scripts",
        '<ul class="bul"><li>Make your scripts flexible and powerful.</li></ul>'
        + term(
            '<span class="c">#!/bin/bash</span>\n'
            '<span class="v">APP_NAME</span>=<span class="s">"MyApp"</span>\n'
            '<span class="v">LOG_DIR</span>=<span class="s">"$HOME/logs"</span>\n'
            '<span class="k">mkdir</span> -p "$LOG_DIR"\n'
            '<span class="k">echo</span> <span class="s">"Starting $APP_NAME...."</span>\n'
            '<span class="k">echo</span> <span class="s">"Logs will be saved in $LOG_DIR"</span>'
        ),
        head_icon="shell", head_icon_size=16)}

      {card("9. Best Practices",
        '<ul class="bul ck">'
        '<li>Always use quotes when in doubt.</li>'
        '<li>Use meaningful variable names.</li>'
        '<li>Export only what you need.</li>'
        '<li>Keep variables uppercase for constants.</li>'
        '<li>Use command substitution <code class="inl navy">$( )</code> often.</li>'
        '<li>Test your scripts with different values.</li>'
        '</ul>',
        head_cls="gold", head_icon="check-circle", head_icon_size=16)}
    </div>
    """

    tip = tip_bar(
        "<b>TIP:</b> Variables are the foundation of flexible scripts. "
        "Quote strings, name clearly, export only what you need.")

    content = inline_css(SHARED_CSS) + header + \
        f'<div class="row-stack">{row1}{row2}{row3}{row4}</div>' + tip
    return page_wrapper(content, paper_height=1424, page_id="p6")


# ============================================================
# PAGE 7 — EXIT CODES AND COMMAND SUCCESS (3-col)
# ============================================================

def build_page_7() -> str:
    title = "6. Exit Codes and Command Success"
    subtitle = "Every command returns a status."
    page_num = "Page 6"

    header = page_header(title, subtitle, page_num,
                         left_icon="terminal", right_icon="check-circle")

    # Row 1 — What exit codes mean + Basic exit code rules
    row1 = f"""
    <div class="grid-2-uneven">
      {card("1. What Exit Codes Mean",
        '<p class="small">After any command runs, the system returns a number called an '
        '<b>exit code</b>. It tells you if the command succeeded or failed.</p>'
        + code_light('<span class="k">echo</span> $?')
        + '<div class="small muted" style="margin-top:4px;">Shows the exit code of the last command.</div>',
        head_icon="question", head_icon_size=16)}

      {card("2. Basic Exit Code Rules",
        '<div style="display:flex;flex-direction:column;gap:8px;">'
        '<div style="display:flex;align-items:center;gap:8px;">'
        f'<div style="flex-shrink:0;width:32px;height:32px;border-radius:50%;'
        f'background:{GREEN};color:#fff;display:flex;align-items:center;'
        f'justify-content:center;font-weight:800;font-size:14px;">0</div>'
        '<div><b style="color:'+GREEN+'">Exit Code 0 · Success</b>'
        '<div class="small muted">Command completed successfully.</div></div>'
        '</div>'
        '<div style="display:flex;align-items:center;gap:8px;">'
        f'<div style="flex-shrink:0;width:32px;height:32px;border-radius:50%;'
        f'background:{RED};color:#fff;display:flex;align-items:center;'
        f'justify-content:center;font-weight:800;font-size:11px;">1+</div>'
        '<div><b style="color:'+RED+'">Non-zero · Failure</b>'
        '<div class="small muted">Something went wrong. Check the error.</div></div>'
        '</div>'
        '</div>',
        head_cls="red", head_icon="warning", head_icon_size=16)}
    </div>
    """

    # Row 2 — Examples (3-col: ls /home, ls /notfound, cat file.txt)
    row2 = f"""
    <div class="grid-3">
      {card("3a. Valid Path",
        code_light('<span class="k">ls</span> /home')
        + '<div class="arrow small" style="margin-top:4px;"></div>'
        + code_light('<span class="k">echo</span> $?')
        + out("0"),
        head_icon="folder", head_icon_size=16)}

      {card("3b. Missing Path",
        code_light('<span class="k">ls</span> /notfoundfolder')
        + code_light('<span class="k">echo</span> $?')
        + '<div class="out" style="color:'+RED+';background:#fce8e8;border-color:#f3c2c2;">'
        + '<svg viewBox="0 0 24 24" fill="none" stroke="'+RED+'" stroke-width="3" '
        + 'stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14"/>'
        + '<path d="M13 6l6 6-6 6"/></svg>'
        + '<span>Output: <b style="color:'+RED+'">2</b></span></div>',
        head_cls="red", head_icon="warning", head_icon_size=16)}

      {card("3c. Read File",
        code_light('<span class="k">cat</span> file.txt')
        + code_light('<span class="k">echo</span> $?')
        + out("0 or 1+"),
        head_icon="file", head_icon_size=16)}
    </div>
    """

    # Row 3 — exit command + testing command success (2-col)
    row3 = f"""
    <div class="grid-2">
      {card("4. The exit Command",
        '<ul class="bul">'
        '<li>Use <code class="inl">exit</code> to end a script and return a code.</li>'
        '<li><code class="inl navy">exit 0</code> = success</li>'
        '<li><code class="inl red">exit 1</code> = failure</li>'
        '<li>Ends the script with a status.</li>'
        '</ul>'
        + term(
            '<span class="k">if</span> [ ! -f file.txt ]; <span class="k">then</span>\n'
            '  <span class="k">echo</span> <span class="s">"File not found!"</span>\n'
            '  <span class="k">exit</span> 1\n'
            '<span class="k">fi</span>'
        ),
        head_icon="arrow", head_icon_size=16)}

      {card("5. Testing Command Success",
        '<ul class="bul"><li>Use exit codes in conditions.</li></ul>'
        + term(
            '<span class="k">ls</span> /home\n'
            '<span class="k">if</span> [ $? -eq 0 ]; <span class="k">then</span>\n'
            '  <span class="k">echo</span> <span class="s">"Success"</span>\n'
            '<span class="k">else</span>\n'
            '  <span class="k">echo</span> <span class="s">"Failed"</span>\n'
            '<span class="k">fi</span>'
        )
        + '<div style="display:flex;gap:6px;margin-top:6px;flex-wrap:wrap;">'
        + '<span class="pill ok"><code class="inl" style="background:transparent;padding:0;">$? -eq 0</code> Success</span>'
        + '<span class="pill no"><code class="inl" style="background:transparent;padding:0;color:'+RED+';">$? -ne 0</code> Failure</span>'
        + '</div>',
        head_icon="check-circle", head_icon_size=16)}
    </div>
    """

    # Row 4 — Why CI/CD depends on exit codes + Preventing failures (2-col)
    row4 = f"""
    <div class="grid-2">
      {card("6. Why CI/CD Depends on Exit Codes",
        '<ul class="bul">'
        '<li>Each step returns an exit code.</li>'
        '<li>CI/CD tools stop the pipeline on failure.</li>'
        '<li><code class="inl">0</code> = pipeline continues.</li>'
        '<li><code class="inl red">1+</code> = pipeline fails.</li>'
        '<li>Ensures reliable and consistent deployments.</li>'
        '</ul>'
        + '<div style="display:flex;align-items:center;gap:6px;margin-top:8px;justify-content:center;">'
        + '<span class="pill ok">Play</span>'
        + '<span class="muted small">→</span>'
        + '<span class="pill ok">Gear</span>'
        + '<span class="muted small">→</span>'
        + '<span class="pill ok">Check</span>'
        + '</div>',
        head_icon="gear", head_icon_size=16)}

      {card("7. Preventing Silent Automation Failures",
        '<ul class="bul ck">'
        '<li><b>Always check exit codes.</b> Don\'t ignore command results.</li>'
        '<li><b>Use <code class="inl navy">set -e</code>.</b> Stops the script on first failure.</li>'
        '<li><b>Log errors clearly.</b> Makes debugging much easier.</li>'
        '<li><b>Validate inputs before running.</b> Bad inputs cause unexpected failures.</li>'
        '<li><b>Test your scripts regularly.</b> Catches issues early.</li>'
        '</ul>',
        head_cls="gold", head_icon="shield", head_icon_size=16)}
    </div>
    """

    tip = tip_bar(
        "<b>TIP:</b> Never ignore exit codes. Check them, handle them, and your "
        "scripts will be reliable and safe.")

    content = inline_css(SHARED_CSS) + header + \
        f'<div class="row-stack">{row1}{row2}{row3}{row4}</div>' + tip
    return page_wrapper(content, paper_height=1424, page_id="p7")


# ============================================================
# PAGE 8 — CONDITIONAL STATEMENTS (3-col)
# ============================================================

def build_page_8() -> str:
    title = "7. Conditional Statements"
    subtitle = "Make smart decisions in your scripts."
    page_num = "Page 7"

    header = page_header(title, subtitle, page_num,
                         left_icon="terminal", right_icon="code")

    # Row 1 — Basic Syntax (with legend) + Numeric Comparisons table
    legend_html = (
        '<div style="display:grid;grid-template-columns:auto 1fr;gap:4px 8px;'
        'font-size:10.5px;margin-top:6px;">'
        '<code class="inl navy">if</code><span class="muted">Start condition</span>'
        '<code class="inl navy">then</code><span class="muted">Run if true</span>'
        '<code class="inl navy">elif</code><span class="muted">Else if another condition</span>'
        '<code class="inl navy">else</code><span class="muted">Run if all false</span>'
        '<code class="inl navy">fi</code><span class="muted">End condition</span>'
        '</div>'
    )
    basic_syntax = (
        code_light(
            '<span class="k">if</span> [ condition ]; <span class="k">then</span>\n'
            '    commands\n'
            '<span class="k">elif</span> [ condition ]; <span class="k">then</span>\n'
            '    commands\n'
            '<span class="k">else</span>\n'
            '    commands\n'
            '<span class="k">fi</span>'
        ) + legend_html
    )

    row1 = f"""
    <div class="grid-2-uneven">
      {card("1. Basic Syntax", basic_syntax,
        head_icon="code", head_icon_size=16)}

      {card("2. Numeric Comparisons",
        '<table class="dt">'
        '<tr><th>Op</th><th>Meaning</th></tr>'
        '<tr><td><code>-eq</code></td><td>Equal</td></tr>'
        '<tr><td><code>-ne</code></td><td>Not equal</td></tr>'
        '<tr><td><code>-gt</code></td><td>Greater than</td></tr>'
        '<tr><td><code>-lt</code></td><td>Less than</td></tr>'
        '<tr><td><code>-ge</code></td><td>Greater or equal</td></tr>'
        '<tr><td><code>-le</code></td><td>Less or equal</td></tr>'
        '</table>'
        + code_light('<span class="k">if</span> [ $a -eq $b ]'),
        head_cls="navy", head_icon="chart", head_icon_size=16)}
    </div>
    """

    # Row 2 — String Comparisons + File Tests (2-col)
    row2 = f"""
    <div class="grid-2">
      {card("3. String Comparisons",
        '<table class="dt">'
        '<tr><th>Op</th><th>Meaning</th></tr>'
        '<tr><td><code>=</code></td><td>Equal</td></tr>'
        '<tr><td><code>!=</code></td><td>Not equal</td></tr>'
        '<tr><td><code>-z</code></td><td>String is empty</td></tr>'
        '<tr><td><code>-n</code></td><td>String not empty</td></tr>'
        '</table>'
        + code_light('<span class="k">if</span> [ "$a" = "$b" ]')
        + '<div style="display:flex;align-items:center;gap:6px;margin-top:6px;'
        'background:#fdf6e3;border:1px solid #e8d68a;border-radius:6px;padding:6px 9px;">'
        + icon("lightbulb", 16) +
        '<span class="small"><b>Note:</b> Always quote strings! Prevents errors with spaces.</span>'
        '</div>',
        head_cls="amber", head_icon="lightbulb", head_icon_size=16)}

      {card("4. File Tests",
        '<table class="dt">'
        '<tr><th>Op</th><th>Meaning</th></tr>'
        '<tr><td><code>-f</code></td><td>File exists</td></tr>'
        '<tr><td><code>-d</code></td><td>Directory exists</td></tr>'
        '<tr><td><code>-e</code></td><td>File or dir exists</td></tr>'
        '<tr><td><code>-r</code></td><td>Readable</td></tr>'
        '<tr><td><code>-w</code></td><td>Writable</td></tr>'
        '<tr><td><code>-x</code></td><td>Executable</td></tr>'
        '<tr><td><code>-s</code></td><td>File is not empty</td></tr>'
        '</table>'
        + code_light('<span class="k">if</span> [ -f file.txt ]'),
        head_icon="file", head_icon_size=16)}
    </div>
    """

    # Row 3 — Checking Services/Files/Directories (3-col)
    row3 = f"""
    <div class="grid-3">
      {card("5a. Check File",
        term(
            '<span class="k">if</span> [ -f /etc/passwd ]; <span class="k">then</span>\n'
            '  <span class="k">echo</span> <span class="s">"File exists"</span>\n'
            '<span class="k">else</span>\n'
            '  <span class="k">echo</span> <span class="s">"File not found"</span>\n'
            '<span class="k">fi</span>'
        ),
        head_icon="file", head_icon_size=16)}

      {card("5b. Check Directory",
        term(
            '<span class="k">if</span> [ -d /var/log ]; <span class="k">then</span>\n'
            '  <span class="k">echo</span> <span class="s">"Directory exists"</span>\n'
            '<span class="k">else</span>\n'
            '  <span class="k">echo</span> <span class="s">"Directory not found"</span>\n'
            '<span class="k">fi</span>'
        ),
        head_cls="navy", head_icon="folder", head_icon_size=16)}

      {card("5c. Check Service",
        term(
            '<span class="k">if</span> systemctl is-active --quiet nginx; <span class="k">then</span>\n'
            '  <span class="k">echo</span> <span class="s">"Nginx is running"</span>\n'
            '<span class="k">else</span>\n'
            '  <span class="k">echo</span> <span class="s">"Nginx is not running"</span>\n'
            '<span class="k">fi</span>'
        ),
        head_cls="blue", head_icon="server", head_icon_size=16)}
    </div>
    """

    # Row 4 — Practical Example + Quick Reference (2-col)
    row4 = f"""
    <div class="grid-2-uneven">
      {card("6. Practical Example",
        '<div class="small muted">Check disk space and act based on the result.</div>'
        + term(
            '<span class="v">USAGE</span>=$(<span class="k">df</span> / | <span class="k">awk</span> \'NR==2 {print $5}\' | <span class="k">tr</span> -d \'%\')\n'
            '<span class="k">if</span> [ "$USAGE" -gt 80 ]; <span class="k">then</span>\n'
            '    <span class="k">echo</span> <span class="s">"Disk usage is high: ${USAGE}%"</span>\n'
            '<span class="k">elif</span> [ "$USAGE" -gt 60 ]; <span class="k">then</span>\n'
            '    <span class="k">echo</span> <span class="s">"Disk usage is moderate: ${USAGE}%"</span>\n'
            '<span class="k">else</span>\n'
            '    <span class="k">echo</span> <span class="s">"Disk usage is normal: ${USAGE}%"</span>\n'
            '<span class="k">fi</span>'
        ),
        head_icon="chart", head_icon_size=16)}

      {card("7. Quick Reference",
        '<ul class="bul ck">'
        '<li><code class="inl navy">if</code> Start condition</li>'
        '<li><code class="inl navy">then</code> Run if true</li>'
        '<li><code class="inl navy">elif</code> Else if</li>'
        '<li><code class="inl navy">else</code> Run if all false</li>'
        '<li><code class="inl navy">fi</code> End condition</li>'
        '<li>Use spaces inside <code class="inl">[ ]</code>.</li>'
        '<li>Quote strings.</li>'
        '<li>Use numeric operators without quotes.</li>'
        '<li>Test before you act.</li>'
        '<li>Make scripts smart and reliable.</li>'
        '</ul>',
        head_cls="gold", head_icon="check-square", head_icon_size=16)}
    </div>
    """

    tip = tip_bar(
        "<b>TIP:</b> Conditions make your scripts intelligent. Always test, "
        "validate, and handle every situation.")

    content = inline_css(SHARED_CSS) + header + \
        f'<div class="row-stack">{row1}{row2}{row3}{row4}</div>' + tip
    return page_wrapper(content, paper_height=1424, page_id="p8")


# ============================================================
# PAGE 9 — LOGICAL OPERATORS AND MULTIPLE CONDITIONS
# (single-column centered)
# ============================================================

def build_page_9() -> str:
    title = "8. Logical Operators and Multiple Conditions"
    subtitle = "Combine tests. Make smarter decisions."
    page_num = "Page 8"

    header = page_header(title, subtitle, page_num,
                         left_icon="terminal", right_icon="branch")

    # Section 1 — Logical Operators table (full-width)
    sec1 = f"""
    {card("1. Logical Operators",
      '<table class="dt">'
      '<tr><th>Operator</th><th>Meaning</th><th>Example</th><th>Description</th></tr>'
      '<tr><td><code>&amp;&amp;</code></td><td>AND</td>'
      '<td><code>if [ $a -gt 5 ] &amp;&amp; [ $b -lt 10 ]</code></td>'
      '<td>Both conditions must be true.</td></tr>'
      '<tr><td><code>||</code></td><td>OR</td>'
      '<td><code>if [ $a -gt 5 ] || [ $b -lt 10 ]</code></td>'
      '<td>At least one condition must be true.</td></tr>'
      '<tr><td><code>!</code></td><td>NOT</td>'
      '<td><code>if ! [ -f file.txt ]</code></td>'
      '<td>Reverses the result.</td></tr>'
      '</table>',
      head_icon="code", head_icon_size=16)}
    """

    # Section 2 — Short-circuit execution (full-width with 3 inline cards)
    sec2 = f"""
    {card("2. Short-Circuit Execution",
      '<div class="grid-3" style="margin-top:4px;">'
      '<div style="background:#eef5ee;border:1px solid #c2ddc8;border-radius:8px;padding:8px 10px;">'
      '<div style="display:flex;align-items:center;gap:6px;margin-bottom:4px;">'
      f'<div style="width:22px;height:22px;border-radius:50%;background:{GREEN};color:#fff;'
      'display:flex;align-items:center;justify-content:center;font-weight:800;font-size:11px;">&amp;&amp;</div>'
      '<b style="color:'+GREEN+'">AND</b></div>'
      '<div class="small">If the first condition is false, the second is NOT executed.</div></div>'
      '<div style="background:#eef5ee;border:1px solid #c2ddc8;border-radius:8px;padding:8px 10px;">'
      '<div style="display:flex;align-items:center;gap:6px;margin-bottom:4px;">'
      f'<div style="width:22px;height:22px;border-radius:50%;background:{GREEN};color:#fff;'
      'display:flex;align-items:center;justify-content:center;font-weight:800;font-size:11px;">||</div>'
      '<b style="color:'+GREEN+'">OR</b></div>'
      '<div class="small">If the first condition is true, the second is NOT executed.</div></div>'
      '<div style="background:#eef5ee;border:1px solid #c2ddc8;border-radius:8px;padding:8px 10px;">'
      '<div style="display:flex;align-items:center;gap:6px;margin-bottom:4px;">'
      f'<div style="width:22px;height:22px;border-radius:50%;background:{GREEN};color:#fff;'
      'display:flex;align-items:center;justify-content:center;font-weight:800;font-size:13px;">!</div>'
      '<b style="color:'+GREEN+'">NOT</b></div>'
      '<div class="small">Flips true to false, and false to true.</div></div>'
      '</div>'
      + '<div style="display:flex;align-items:center;gap:6px;margin-top:8px;'
      'background:#fdf6e3;border:1px solid #e8d68a;border-radius:6px;padding:6px 10px;">'
      + icon("lightbulb", 18) +
      '<span class="small"><b>Insight:</b> Saves time and prevents unnecessary checks.</span></div>',
      head_cls="amber", head_icon="lightbulb", head_icon_size=16)}
    """

    # Section 3-5 — AND / OR / NOT (3-col)
    sec345 = f"""
    <div class="grid-3">
      {card("3. AND (&&)",
        '<ul class="bul"><li>Both conditions must be true.</li></ul>'
        + term(
            '<span class="k">if</span> [ -f app.sh ] &amp;&amp; [ -x app.sh ]; <span class="k">then</span>\n'
            '  <span class="k">echo</span> <span class="s">"File exists and is executable"</span>\n'
            '<span class="k">else</span>\n'
            '  <span class="k">echo</span> <span class="s">"Check failed"</span>\n'
            '<span class="k">fi</span>'
        )
        + '<div class="small muted" style="margin-top:4px;">'
        + icon("check-circle", 14) +
        ' Use for strict requirements.</div>',
        head_icon="check-circle", head_icon_size=16)}

      {card("4. OR (||)",
        '<ul class="bul"><li>At least one condition must be true.</li></ul>'
        + term(
            '<span class="k">if</span> [ -f app.sh ] || [ -f app.py ]; <span class="k">then</span>\n'
            '  <span class="k">echo</span> <span class="s">"Script found"</span>\n'
            '<span class="k">else</span>\n'
            '  <span class="k">echo</span> <span class="s">"No script found"</span>\n'
            '<span class="k">fi</span>'
        )
        + '<div class="small muted" style="margin-top:4px;">'
        + icon("check-circle", 14) +
        ' Use for alternatives.</div>',
        head_cls="navy", head_icon="check-circle", head_icon_size=16)}

      {card("5. NOT (!)",
        '<ul class="bul"><li>Reverse a condition.</li></ul>'
        + term(
            '<span class="k">if</span> [ ! -f config.env ]; <span class="k">then</span>\n'
            '  <span class="k">echo</span> <span class="s">"Config file missing"</span>\n'
            '<span class="k">else</span>\n'
            '  <span class="k">echo</span> <span class="s">"Config file exists"</span>\n'
            '<span class="k">fi</span>'
        )
        + '<div class="small muted" style="margin-top:4px;">'
        + icon("check-circle", 14) +
        ' Use to detect missing items.</div>',
        head_cls="purple", head_icon="search", head_icon_size=16)}
    </div>
    """

    # Section 6 — Combining multiple tests (3-col, examples 1, 2, 3)
    sec6 = f"""
    {card("6. Combining Multiple Tests",
      '<div class="small muted" style="margin-bottom:6px;">You can mix '
      '<code class="inl">&amp;&amp;</code>, <code class="inl">||</code>, and '
      '<code class="inl">!</code> for powerful checks.</div>'
      + '<div class="grid-3">'
      + '<div class="card"><div class="head">Example 1: Mix AND &amp; OR</div><div class="pad tight">'
      + term(
          '<span class="k">if</span> [ -f deploy.sh ] &amp;&amp;\n'
          '   [ -x deploy.sh ] ||\n'
          '   [ -f deploy.py ]; <span class="k">then</span>\n'
          '  <span class="k">echo</span> <span class="s">"Ready to deploy"</span>\n'
          '<span class="k">else</span>\n'
          '  <span class="k">echo</span> <span class="s">"Deployment script missing"</span>\n'
          '<span class="k">fi</span>'
      ) + '<div class="small muted" style="margin-top:4px;">➔ Executable deploy.sh OR deploy.py exists.</div>'
      + '</div></div>'
      + '<div class="card"><div class="head navy">Example 2: Negation + AND</div><div class="pad tight">'
      + term(
          '<span class="k">if</span> [ ! -f .lock ] &amp;&amp;\n'
          '   [ -d /var/log ]; <span class="k">then</span>\n'
          '  <span class="k">echo</span> <span class="s">"Safe to proceed"</span>\n'
          '<span class="k">else</span>\n'
          '  <span class="k">echo</span> <span class="s">"Lock exists or log dir missing"</span>\n'
          '<span class="k">fi</span>'
      ) + '<div class="small muted" style="margin-top:4px;">➔ No lock file AND directory exists.</div>'
      + '</div></div>'
      + '<div class="card"><div class="head purple">Example 3: Complex</div><div class="pad tight">'
      + term(
          '<span class="k">if</span> [ -f app.conf ] &amp;&amp;\n'
          '   [ -r app.conf ] &amp;&amp;\n'
          '   ! [ -z "$1" ]; <span class="k">then</span>\n'
          '  <span class="k">echo</span> <span class="s">"All checks passed"</span>\n'
          '<span class="k">else</span>\n'
          '  <span class="k">echo</span> <span class="s">"Validation failed"</span>\n'
          '<span class="k">fi</span>'
      ) + '<div class="small muted" style="margin-top:4px;">➔ File exists, readable AND $1 not empty.</div>'
      + '</div></div>'
      + '</div>',
      head_cls="teal", head_icon="branch", head_icon_size=16)}
    """

    # Section 7 — Building Safer Deployment Checks (2-col)
    sec7 = f"""
    <div class="grid-2-uneven">
      {card("7. Building Safer Deployment Checks",
        '<div class="small muted" style="margin-bottom:4px;">'
        '<b>Example:</b> Before deploying, validate everything.</div>'
        + term(
            '<span class="k">if</span> [ -f app.tar.gz ] &amp;&amp;\n'
            '   [ -s app.tar.gz ] &amp;&amp;\n'
            '   [ -x /usr/bin/docker ] &amp;&amp;\n'
            '   ! systemctl is-active --quiet app; <span class="k">then</span>\n'
            '  <span class="k">echo</span> <span class="s">"All checks passed. Starting deployment..."</span>\n'
            '  <span class="c"># Your deployment commands here</span>\n'
            '<span class="k">else</span>\n'
            '  <span class="k">echo</span> <span class="s">"Deployment aborted. Check requirements."</span>\n'
            '  <span class="k">exit</span> 1\n'
            '<span class="k">fi</span>'
        ),
        head_icon="rocket", head_icon_size=16)}

      {card("Deployment Checklist",
        '<ul class="bul ck">'
        '<li>File exists AND not empty.</li>'
        '<li>Docker is installed.</li>'
        '<li>App service is not running.</li>'
        '<li>Proceed only when everything is correct.</li>'
        '<li>Prevents failed or risky deployments.</li>'
        '</ul>'
        + '<div style="display:flex;align-items:center;gap:8px;margin-top:8px;'
        'background:'+GREEN+';color:#fff;border-radius:8px;padding:8px 12px;">'
        + icon("shield", 22) +
        '<b style="font-size:11.5px;letter-spacing:.6px;">SAFE DEPLOYMENT STARTS HERE!</b></div>',
        head_cls="gold", head_icon="shield", head_icon_size=16)}
    </div>
    """

    tip = tip_bar(
        "<b>TIP:</b> Combine checks, validate early, and fail fast. "
        "Smart conditions = reliable automation.")

    content = inline_css(SHARED_CSS) + header + \
        f'<div class="single-wrap">{sec1}{sec2}{sec345}{sec6}{sec7}</div>' + tip
    return page_wrapper(content, paper_height=1424, page_id="p9")


# ============================================================
# PAGE 10 — LOOPS FOR AUTOMATION (2-col)
# ============================================================

def build_page_10() -> str:
    title = "9. Loops for Automation"
    subtitle = "Repeat tasks. Save time. Eliminate manual work."
    page_num = "Page 9"

    header = page_header(title, subtitle, page_num,
                         left_icon="refresh", right_icon="gear")

    # Left column — Sections 1, 3, 5, 7  (per analysis)
    left_col = f"""
    <div class="col-stack">

      {card("1. For Loops",
        '<ul class="bul"><li>Loop through a list of items.</li></ul>'
        + term(
            '<span class="k">for</span> item <span class="k">in</span> a b c; <span class="k">do</span>\n'
            '    <span class="k">echo</span> <span class="s">"Item: $item"</span>\n'
            '<span class="k">done</span>'
        )
        + out("Item: a  Item: b  Item: c"),
        head_icon="arrow", head_icon_size=16)}

      {card("3. Looping Through Files",
        '<ul class="bul"><li>Process each file in a directory.</li></ul>'
        + term(
            '<span class="k">for</span> file <span class="k">in</span> *.txt; <span class="k">do</span>\n'
            '    <span class="k">echo</span> <span class="s">"File: $file"</span>\n'
            '<span class="k">done</span>'
        )
        + '<div class="small muted" style="margin-top:4px;">Prints all .txt files in the current directory.</div>',
        head_icon="file", head_icon_size=16)}

      {card("5. Break",
        '<ul class="bul"><li>Exit the loop immediately.</li></ul>'
        + '<div style="display:inline-flex;align-items:center;gap:5px;'
        'background:'+RED+';color:#fff;padding:3px 9px;border-radius:5px;'
        'font-size:10.5px;font-weight:800;letter-spacing:.5px;text-transform:uppercase;">'
        + icon("stop", 14) + 'STOP THE LOOP</div>'
        + term(
            '<span class="k">for</span> i <span class="k">in</span> {1..5}; <span class="k">do</span>\n'
            '    <span class="k">if</span> [ $i -eq 3 ]; <span class="k">then</span>\n'
            '        <span class="k">break</span>\n'
            '    <span class="k">fi</span>\n'
            '    <span class="k">echo</span> <span class="s">"Number: $i"</span>\n'
            '<span class="k">done</span>'
        )
        + out("Number: 1  Number: 2"),
        head_cls="red", head_icon="stop", head_icon_size=16)}

      {card("7. Avoiding Infinite Loops",
        '<ul class="bul ck">'
        '<li>Always update your condition.</li>'
        '<li>Always change the variable inside the loop.</li>'
        '<li>Use clear exit conditions.</li>'
        '<li>Test your loops with small values first.</li>'
        '<li>Use <code class="inl navy">break</code> when needed.</li>'
        '</ul>'
        + '<div style="display:flex;align-items:center;gap:6px;margin-top:6px;'
        'background:#fdf6e3;border:1px solid #e8d68a;border-radius:6px;padding:6px 9px;">'
        + icon("warning", 18) +
        '<span class="small" style="color:#8a6810;font-weight:800;letter-spacing:.4px;">BE CAREFUL</span></div>',
        head_cls="amber", head_icon="warning", head_icon_size=16)}

    </div>
    """

    # Right column — Sections 2, 4, 6, 8
    right_col = f"""
    <div class="col-stack">

      {card("2. While Loops",
        '<ul class="bul"><li>Repeat while a condition is true.</li></ul>'
        + term(
            '<span class="v">count</span>=1\n'
            '<span class="k">while</span> [ $count -le 5 ]; <span class="k">do</span>\n'
            '    <span class="k">echo</span> <span class="s">"Count: $count"</span>\n'
            '    count=$((count + 1))\n'
            '<span class="k">done</span>'
        )
        + out("Count: 1  2  3  4  5"),
        head_cls="navy", head_icon="refresh", head_icon_size=16)}

      {card("4. Looping Through Servers",
        '<ul class="bul"><li>Run commands on multiple servers.</li></ul>'
        + term(
            '<span class="k">for</span> server <span class="k">in</span> server1 server2 server3; <span class="k">do</span>\n'
            '    <span class="k">echo</span> <span class="s">"Checking $server..."</span>\n'
            '    <span class="k">ssh</span> $server uptime\n'
            '<span class="k">done</span>'
        )
        + '<div class="small muted" style="margin-top:4px;">Check uptime on many servers.</div>',
        head_cls="blue", head_icon="server", head_icon_size=16)}

      {card("6. Continue",
        '<ul class="bul"><li>Skip the rest of the loop and continue.</li></ul>'
        + '<div style="display:inline-flex;align-items:center;gap:5px;'
        'background:'+GREEN+';color:#fff;padding:3px 9px;border-radius:5px;'
        'font-size:10.5px;font-weight:800;letter-spacing:.5px;text-transform:uppercase;">'
        + icon("refresh", 14) + 'SKIP AND CONTINUE</div>'
        + term(
            '<span class="k">for</span> i <span class="k">in</span> {1..5}; <span class="k">do</span>\n'
            '    <span class="k">if</span> [ $i -eq 3 ]; <span class="k">then</span>\n'
            '        <span class="k">continue</span>\n'
            '    <span class="k">fi</span>\n'
            '    <span class="k">echo</span> <span class="s">"Number: $i"</span>\n'
            '<span class="k">done</span>'
        )
        + out("Number: 1  2  4  5"),
        head_icon="refresh", head_icon_size=16)}

      {card("8. Automating Repetitive Tasks",
        '<div class="small" style="margin-bottom:4px;">Loops help you automate daily tasks:</div>'
        '<ul class="bul ck">'
        '<li>File management</li>'
        '<li>Server monitoring</li>'
        '<li>User management</li>'
        '<li>Log analysis</li>'
        '<li>Backups and cleanups</li>'
        '<li>System updates</li>'
        '</ul>'
        + '<div style="display:flex;align-items:center;gap:6px;margin-top:6px;'
        'background:'+GREEN+';color:#fff;border-radius:6px;padding:6px 10px;">'
        + icon("rocket", 18) +
        '<b style="font-size:11px;letter-spacing:.5px;">AUTOMATE EVERYTHING</b></div>',
        head_cls="gold", head_icon="rocket", head_icon_size=16)}

    </div>
    """

    # Key takeaway bar
    takeaway = f"""
    <div class="tip-bar" style="background:linear-gradient(90deg,{GOLD} 0%, {AMBER} 100%);color:#1c1c1c;">
      <div class="star" style="background:{GREEN};">
        {icon("lightbulb", 18).replace("#f9a825", "#fff").replace("#e0a517", "#fff").replace("#d4a017", "#fff").replace("#b8860b", "#fff")}
      </div>
      <div class="txt">
        <b>KEY TAKEAWAY:</b> Loops save time, reduce errors, and make your scripts powerful.
      </div>
      <div class="code-pill" style="background:"+GREEN+";color:#fff;">REPEAT SMARTER · SAVE TIME EVERY DAY</div>
    </div>
    """

    content = inline_css(SHARED_CSS) + header + \
        f'<div class="grid-2">{left_col}{right_col}</div>' + takeaway
    return page_wrapper(content, paper_height=1424, page_id="p10")


# ============================================================
# Build + write all 5 pages
# ============================================================

PAGES = [
    ("06", build_page_6,  "Shell Scripting — Page 6: Variables & Environment Variables"),
    ("07", build_page_7,  "Shell Scripting — Page 7: Exit Codes & Command Success"),
    ("08", build_page_8,  "Shell Scripting — Page 8: Conditional Statements"),
    ("09", build_page_9,  "Shell Scripting — Page 9: Logical Operators & Multiple Conditions"),
    ("10", build_page_10, "Shell Scripting — Page 10: Loops for Automation"),
]


def main() -> None:
    os.makedirs(OUT_DIR, exist_ok=True)
    written = []
    for num, builder, title in PAGES:
        page_html = builder()
        # Wrap the single page in a full standalone HTML document
        doc = multi_page_html([page_html], title)
        out_path = os.path.join(OUT_DIR, f"recreated-page-{num}.html")
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(doc)
        written.append((out_path, len(doc)))
        print(f"  wrote {out_path}  ({len(doc):,} bytes)")
    print(f"\nWrote {len(written)} pages to {OUT_DIR}")


if __name__ == "__main__":
    main()
